FROM python:3.10-slim
ENV OPENBLAS_CORETYPE=Haswell

WORKDIR /app

COPY ui/requirements.txt ui/requirements.txt
RUN pip install --no-cache-dir -r ui/requirements.txt

COPY ui/ ui/

EXPOSE 8501

CMD ["streamlit", "run", "ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
